### send Message
POST https://graph.facebook.com/v12.0/100230876128607/messages?access_token=EABN2iUGxGNIBAK2QQyZCIZBCxS5rIUj5QKQ4AeaKsiQgglbPNijixoZCqfDwOko5tVAnfWZAnizvjH5FZAIlASPNsR37IJoc4xoF1BnmxDZAgMgq1SAwvyZCZAlEuXujIGG2tj73SsVfq0JZA8VvG4IANV2ZCU9uWZBZBjjFKvr5zsVbvXmyKtTQgHJlD1xgQt7ou4jlR3TWQpFT7DkQMj5CZAWgK

Content-Type: application/json


## from : 201116273717

###
POST https://graph.facebook.com/v13.0/100230876128607/messages
Content-Type: 'application/json'
Authorization: 'bearer EABN2iUGxGNIBANcxvevlEDrs9npz1oJuz8mWKczOGMieq7BMNPrSRhsSZCmxZABeWz7ZAavoJwPDyFFiChiwMZA5R0VRTmqdXZC2t5SzZCdQFbeZBGGYbo736Rvmnx33yUWjNrOGqbfvEr3n8k2CZCurxE3knc4qAGZCoqrrpB3QHZCMKFMrox5ImKAVSGpyN8SmtZCTPxl8ibZCed9ckF3W5rBl'

{
    "messaging_product": "whatsapp",
    "recipient_type": "individual",
    "to": "201116273717",
    "type": "template",
    "template": {
        "name": "marketing",
        "language": {
            "code": "en_US"
        },
        "components": [
            {
                "type": "header",
                "parameters": [
                    {
                        "type": "image",
                        "image": {
                            "link": "https://upload.wikimedia.org/wikipedia/commons/e/e9/Painting_of_blue-winged_teal_and_scarlet_tanager_birds_by_William_Savage.jpg",
                        },
                    },
                ],
            },
            {
                "type": "body",
                "parameters": [
                    {
                        "type": "text",
                        "text": "productName",
                    }
                ]
            }
        ]
    }
}